// <auto-generated />
using System;
using GraduProjj.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraduProjj.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250505200011_initDB")]
    partial class initDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraduProjj.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<int>("BudgetHelpfulnessRating")
                        .HasColumnType("int");

                    b.Property<string>("ConfusingFeatures")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DesiredFeatures")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImprovementSuggestion")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NavigationEase")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OverallSatisfaction")
                        .HasColumnType("int");

                    b.Property<string>("RecommendationReason")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("SubmissionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("SubmissionDate");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("GraduProjj.Models.Goal", b =>
                {
                    b.Property<int>("GoalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoalID"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GoalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GoalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Has_Savings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("GoalID");

                    b.HasIndex("Status");

                    b.HasIndex("UserID");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("GraduProjj.Models.Input", b =>
                {
                    b.Property<int>("InputID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InputID"));

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("city_tier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dependents")
                        .HasColumnType("int");

                    b.Property<decimal>("eatingOut")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("education")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("entertainment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("groceries")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("healthcare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("income")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("insurance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("loanPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("occupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("otherMoney")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("rent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("transport")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("utilities")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InputID");

                    b.HasIndex("UserID");

                    b.ToTable("Inputs");
                });

            modelBuilder.Entity("GraduProjj.Models.Plan", b =>
                {
                    b.Property<int>("PlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanID"));

                    b.Property<decimal>("EatingOut")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Education")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Entertainment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GoalID")
                        .HasColumnType("int");

                    b.Property<decimal>("Groceries")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Healthcare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlySavings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherMoney")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<decimal>("Transport")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Utilities")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PlanID");

                    b.HasIndex("GoalID");

                    b.HasIndex("Status");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("GraduProjj.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailVerificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("OtpCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OtpExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfilePicturePath")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GraduProjj.Models.Feedback", b =>
                {
                    b.HasOne("GraduProjj.Models.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GraduProjj.Models.Goal", b =>
                {
                    b.HasOne("GraduProjj.Models.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GraduProjj.Models.Input", b =>
                {
                    b.HasOne("GraduProjj.Models.User", "User")
                        .WithMany("Input")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GraduProjj.Models.Plan", b =>
                {
                    b.HasOne("GraduProjj.Models.Goal", "Goal")
                        .WithMany("Plans")
                        .HasForeignKey("GoalID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("GraduProjj.Models.Goal", b =>
                {
                    b.Navigation("Plans");
                });

            modelBuilder.Entity("GraduProjj.Models.User", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Goals");

                    b.Navigation("Input");
                });
#pragma warning restore 612, 618
        }
    }
}
